---
include:
  - board: corne_choc_pro_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: corne_choc_pro_left
  - board: corne_choc_pro_right
    shield: nice_view
    snippet: studio-rpc-usb-uart
    artifact-name: corne_choc_pro_right

  - board: corne_choc_pro_left
    shield: settings_reset
    snippet: studio-rpc-usb-uart
    artifact-name: corne_choc_pro_left_settings_reset
  - board: corne_choc_pro_right
    shield: settings_reset
    snippet: studio-rpc-usb-uart
    artifact-name: corne_choc_pro_right_settings_reset

  - board: piantor_pro_bt_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: piantor_pro_bt_left
  - board: piantor_pro_bt_right
    shield: nice_view
    snippet: studio-rpc-usb-uart
    artifact-name: piantor_pro_bt_right

  - board: piantor_pro_bt_left
    shield: settings_reset
    snippet: studio-rpc-usb-uart
    artifact-name: piantor_pro_bt_left_settings_reset
  - board: piantor_pro_bt_right
    shield: settings_reset
    snippet: studio-rpc-usb-uart
    artifact-name: piantor_pro_bt_right_settings_reset

  - board: sofle_choc_pro_left
    shield: nice_view_disp
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: sofle_choc_pro_left
  - board: sofle_choc_pro_right
    shield: nice_view_disp
    snippet: studio-rpc-usb-uart
    artifact-name: sofle_choc_pro_right

  - board: sofle_choc_pro_left
    shield: settings_reset
    snippet: studio-rpc-usb-uart
    artifact-name: sofle_choc_pro_left_settings_reset
  - board: sofle_choc_pro_right
    shield: settings_reset
    snippet: studio-rpc-usb-uart
    artifact-name: sofle_choc_pro_right_settings_reset
