---
include:
  - board: piantor_pro_bt_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: piantor_pro_bt_left
  - board: piantor_pro_bt_right
    shield: nice_view
    snippet: studio-rpc-usb-uart
    artifact-name: piantor_pro_bt_right
  - board: piantor_pro_bt_left
    shield: settings_reset
    snippet: studio-rpc-usb-uart
    artifact-name: piantor_pro_bt_left_settings_reset
  - board: piantor_pro_bt_right
    shield: settings_reset
    snippet: studio-rpc-usb-uart
    artifact-name: piantor_pro_bt_right_settings_reset
