# Deep sleep after 2 hours of idle
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=7200000

# Increase BT transmit power to max (+8 dBm) for reliable split communication
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
